Configuration:
  Properties:
    property:
      - name: applicationName
        value: eswebapp
      - name: installDirectory
        value: /usr/local/app
      - name: applicationJar
        value: eswebapp-1.0.0-SNAPSHOT
  Appenders:
    RollingFile:
      - name: MetricJsonDailyRollingFileAppenderRef
        fileName: ${installDirectory}/log/${applicationName}/metrics.log
        filePattern: ${installDirectory}/log/${applicationName}/metrics.%d{yyyy-MM-dd}.log
        MetricJsonLayout:
          application: ${applicationName}
          namespace: alces
          locationInfo: true
        Policies:
          CronTriggeringPolicy:
            evaluateOnStartup: true
            schedule: 0 0 0 * * ?
        DefaultRollOverStrategy:
          Delete:
            basePath: ${installDirectory}/log/${applicationName}/
            IfLastModified:
              age: 1d
  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: MetricJsonDailyRollingFileAppenderRef