Configuration:
   Appenders:
      Console:
         name: ConsoleAppender
         target: SYSTEM_OUT
         MetricJsonLayout:
            application: myapp
            namespace: mannetroll
            locationInfo: true
            sort: true            
   Loggers:
      Root:
         level: info
         AppenderRef:
         -  ref: ConsoleAppender