Configuration:
  Appenders:
    Console:
      name: ConsoleAppender
      target: SYSTEM_OUT
      MetricJsonLayout:
        application: myapp
        locationInfo: true
        osInfo: true
  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: ConsoleAppender
