Configuration:
   status: warn

   Appenders:
      Console:
         name: Console_Appender
         target: SYSTEM_OUT
         JsonTemplateLayout:
            eventTemplateUri: classpath:JsonLayout.json

   Loggers:
      Root:
         level: info
         AppenderRef:
         -  ref: Console_Appender